# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_shopkeeper.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Dialog(object):
    def final_submit(self):
        if self.code == int(self.my_lineEdit.text()):
            q1 = f"UPDATE PATIENT set Shop_keeper='{self.shop_keeper}', STATUS='False' where code={self.code}"
            print("\n Medicine given!!!")
            try :
               connection = sqlite3.connect("govind.db")
               connection.execute(q1)
               connection.commit()
            except Exception as e :
               print (e)
            finally:        
               connection.close()



    def submit(self):
        p_aaadhar = int(self.p_aadhar_lineEdit.text())
        username = self.u_name_lineEdit.text()
        self.shop_keeper = username
        password = self.password_lineEdit.text()
        connection = sqlite3.connect("govind.db")
        result = connection.execute("SELECT * FROM SHOPKEEPER WHERE USERNAME = ? AND PASSWORD = ?",(username,password))
        #print(p_aaadhar,type(p_aaadhar))
        if(len(result.fetchall())>0):
            res = connection.execute(f"SELECT * FROM PATIENT WHERE PATIENT_AADHAR = {p_aaadhar} AND STATUS = 'True'")
            #print (res)
            #if(len(res.fetchall())>0):
            res_data = list(res)[0]
            self.med= res_data[4]
            self.code = int(res_data[8])
            #print (self.med)
            self.my_textEdit.setPlainText(self.med)
            #else:
                #print("Medicine already given!!!")
            
            '''
            for data in res:
                print("PATIENT NAME : ",data[0])
                print("PATIENT AGE : ",data[1])
                print("PATIENT GENDER : ",data[2])
                print("PATIENT AADHAR : ",data[3])
                print("MEDICINES : ",data[4])
                print("DOCTOR'S NAME : ",data[5])'''
        else:
            print("WRONG CREDENTIALS!!Or Medicine already given!!!!")
        connection.commit()
        connection.close()
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(847, 632)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(164, 255, 237, 255), stop:1 rgba(255, 255, 255, 255));")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(160, 130, 501, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.p_aadhar_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.p_aadhar_lineEdit.setObjectName("p_aadhar_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.p_aadhar_lineEdit)
        self.u_name_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.u_name_lineEdit.setObjectName("u_name_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.u_name_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(360, 370, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.my_textEdit = QtWidgets.QTextEdit(Dialog)
        self.my_textEdit.setGeometry(QtCore.QRect(90, 460, 251, 87))
        self.my_textEdit.setObjectName("my_textEdit")
        self.my_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.my_lineEdit.setGeometry(QtCore.QRect(520, 510, 131, 31))
        self.my_lineEdit.setObjectName("my_lineEdit")
        self.my_pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.my_pushButton_2.setGeometry(QtCore.QRect(480, 580, 93, 28))
        self.my_pushButton_2.setObjectName("my_pushButton_2")
        self.mylabel_4 = QtWidgets.QLabel(Dialog)
        self.mylabel_4.setGeometry(QtCore.QRect(440, 520, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mylabel_4.setFont(font)
        self.mylabel_4.setObjectName("mylabel_4")
        ########################Event#############
        self.pushButton.clicked.connect(self.submit)
        self.my_pushButton_2.clicked.connect(self.final_submit)
        ################################################

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Patient\'s Aadhar"))
        self.label_2.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "Submit"))
        self.my_pushButton_2.setText(_translate("Dialog", "final submit"))
        self.mylabel_4.setText(_translate("Dialog", "OTP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
