# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup4.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import login_doctor
import login_shopkeeper
import sqlite3

class Ui_signUp(object):

    def loginCheck1(self):
        self.loginShow1()
        
    def loginShow1(self):
        self.loginsWindow = QtWidgets.QDialog()
        self.ui = login_shopkeeper.Ui_Dialog()
        self.ui.setupUi(self.loginsWindow)
        self.loginsWindow.show()

    def loginCheck(self):
        self.loginShow()

    def loginShow(self):
        self.loginWindow = QtWidgets.QMainWindow()
        self.ui = login_doctor.Ui_doctor()
        self.ui.setupUi(self.loginWindow)
        self.loginWindow.show()
    
    #errror mssg display
    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    role = "Not-selected"
    @classmethod
    def radio_doc(cls):
        cls.role = "DOCTOR"
        #print (cls.role)

    @classmethod
    def radio_shop(cls):
        cls.role = "SHOPKEEPER"
        #print (cls.role)

    def insertData(self):
        #role = self.radioButton.text()
        if self.role != "Not-selected":
            username = self.u_name_lineEdit.text()
            name = self.name_lineEdit.text()
            email = self.email_lineEdit.text()
            mobile = self.mobile_lineEdit.text()
            password = self.password_lineEdit.text()
            cnf_password = self.cnf_password_lineEdit.text()
            connection = sqlite3.connect("govind.db")
            if(password == cnf_password):
                if (self.role == 'DOCTOR'):
                    connection.execute("INSERT INTO DOCTOR VALUES(?,?,?,?,?,?,?)",(self.role,username,name,email,mobile,password,cnf_password))
                    print ("Form Submitted as DOCTOR successfully!!!!!")
                    connection.commit()
                    #connection.close()
                else:
                    connection.execute("INSERT INTO SHOPKEEPER VALUES(?,?,?,?,?,?,?)",(self.role,username,name,email,mobile,password,cnf_password))
                    print ("Form Submitted as SHOPKEEPER successfully!!!!!")
                    connection.commit()
                connection.close()
            else:
                print("password and confirm password is not same")
        else :
            print("Please select the role")
            
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(818, 665)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(105, 0, 82, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(110, 150, 571, 216))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.u_name_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.u_name_lineEdit.setObjectName("u_name_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.u_name_lineEdit)
        self.name_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.email_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.email_lineEdit)
        self.mobile_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mobile_lineEdit.setObjectName("mobile_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mobile_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cnf_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cnf_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cnf_password_lineEdit.setObjectName("cnf_password_lineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cnf_password_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 80, 381, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(320, 380, 361, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sign_up_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up_btn.setFont(font)
        self.sign_up_btn.setObjectName("sign_up_btn")
        ############################################################################Event#####################################
        self.sign_up_btn.clicked.connect(self.insertData)
        #############################################################################################################
        self.horizontalLayout_2.addWidget(self.sign_up_btn)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(320, 480, 406, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        ################################### Button event ############################################################
        self.login_btn.clicked.connect(self.loginCheck)
        #############################################################################################################
        self.horizontalLayout_3.addWidget(self.login_btn)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        ################################### Button event ############################################################
        self.pushButton_3.clicked.connect(self.loginCheck1)
        #############################################################################################################
        self.horizontalLayout_3.addWidget(self.pushButton_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "USERNAME"))
        self.label_2.setText(_translate("Dialog", "NAME"))
        self.label_3.setText(_translate("Dialog", "EMAIL"))
        self.label_4.setText(_translate("Dialog", "MOBILE NO."))
        self.label_5.setText(_translate("Dialog", "PASSWORD"))
        self.label_6.setText(_translate("Dialog", "CONFIRM PASSWORD"))
        self.radioButton.setText(_translate("Dialog", "DOCTOR"))
        self.radioButton_2.setText(_translate("Dialog", "SHOPKEEPER"))
        self.sign_up_btn.setText(_translate("Dialog", "SIGN UP"))
        self.login_btn.setText(_translate("Dialog", "LOG IN for DOCTOR"))
        self.pushButton_3.setText(_translate("Dialog", "LOG IN for SHOPKEEPER"))
        self.radioButton.toggled.connect(self.radio_doc)  
        self.radioButton_2.toggled.connect(self.radio_shop)  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_signUp()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
